### PR TITLE
Upgrade Nuget of MassTransit and Service Fabric

### PR DESCRIPTION
**Pull request by heavenwing**

### CODE REVIEW

**Comment by kevbite** [comment]
Do we need `ServiceFabricBackup/**`?

**Comment by kevbite** [comment]
We'll also need to swap out the build image for appveyor to
```
image:
- Visual Studio 2017
```

**Comment by heavenwing** [comment]
Sorry. I forgot to delete this folder. We don't need this.

Gavin

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by heavenwing** [comment]
When can you  switch to Visual Studio 2017 appveyor images?

**Comment by kevbite** [comment]
I've updated master to build with the new images, just pull in master and should be ok.

**Comment by heavenwing** [comment]
After I merged your master, build is still not working.
Maybe it's a problem with ASP.NET Core build configuration?

**Comment by kevbite** [comment]
@heavenwing I'm not sure... looks like build server is moaning at referencing other projects in the solution now. I should have a bit of time tonight to check it out.

**Comment by kevbite** [comment]
@heavenwing sorry for the delay, just figured it out and it was due to it was trying to build it in AnyCPU but ServiceFabric requires x64. Changed and merged your changes in.

Thanks!

**Pull request merged**
